teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [5]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.8
        offset: 0.0
      -
        axis: 3
        target: angular.z
        scale: 1.0
      -
        axis: 0
        target: linear.y
        scale: 0.8


  stop:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [2]
    message_value:
      -
        target: linear.x
        value: 0.0
      -
        target: angular.z
        value: 0.0
      -
        target: linear.y
        value: 0.0

  hello:
    type: topic
    message_type: std_msgs/String
    topic_name: chatter
    deadman_buttons: [1]
    message_value:
      -
        target: data
        value: 'Hello'

